# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l_uweHhkl0jgXPRgFdlMHO-r3VQ7NPQN
"""

import pandas as pd
import seaborn as sns
from datetime import datetime
import numpy as np

data1=pd.read_excel('COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_KeyIndicators')
data2=pd.read_excel('COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_KeyIndicators_Detail')
data3=pd.read_excel('COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_Action_Screen')
data4=pd.read_excel('COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_Action_Call')
data5=pd.read_excel('COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_COVID_News')
data6=pd.read_excel('COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_NIH_Response')
data7=pd.read_excel('COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_NIH_Risk')
data8=pd.read_excel('COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_Province_Response')
data9=pd.read_excel('COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_Helpline_Calls')
data10=pd.read_excel('COVID_FINAL_DATA.xlsx',sheet_name='TimeSeries_Quarantine_Details')

data1.columns=data1.columns.str.strip().str.lower().str.replace(' ','_')
data1.drop(['no_heading'],axis=1,inplace=True)
data1=data1.dropna(how='all')
data1=data1.fillna(0)
data1['date']=pd.to_datetime(data1['date'])
data1['tests__performed_in_last_24_hours']= data1['tests__performed_in_last_24_hours'].apply(np.int64)
data1['tests__performed_in_last_24_hours']=pd.to_numeric(data1['tests__performed_in_last_24_hours'])
data1['home_quarantine']=data1['home_quarantine'].apply(np.int64)
datetime_object=datetime.now() 
print(datetime_object)
data1['date']=pd.to_datetime(data1['date'],format="%d/%m/%y/")
data1['date']=pd.to_datetime(data1['date'])
data1['date']=data1['date'].dt.strftime('%m/%d/%y')



data2.columns=data2.columns.str.strip().str.lower().str.replace(' ','_')
data2['date']=pd.to_datetime(data2['date'])
data2['date']=data2['date'].dt.strftime('%m/%d/%y')

data3.columns=data3.columns.str.strip().str.lower().str.replace(' ','_')
data3['date']=pd.to_datetime(data3['date'])
data3['date']=data3['date'].dt.strftime('%m/%d/%y')



data4.columns=data4.columns.str.strip().str.lower().str.replace(' ','-')
data4['date']=pd.to_datetime(data4['date'])
data4['date']=data4['date'].dt.strftime('%m/%d/%y')

data5.columns=data5.columns.str.strip().str.lower().str.replace(' ','-')
data5.drop(['no_heading'],axis=1,inplace=True)
data5['date']=pd.to_datetime(data5['date'])
data5['date']=data5['date'].dt.strftime('%m/%d/%y')
data5.isnull().sum()



data6.columns=data6.columns.str.strip().str.lower().str.replace(' ','-')
data6.drop(['no_heading'],axis=1,inplace=True)
data6['date']=pd.to_datetime(data6['date'])
data6['date']=data6['date'].dt.strftime('%m/%d/%y')



data7.columns=data7.columns.str.strip().str.lower().str.replace(' ','-')
data7.drop(['no_heading'],axis=1,inplace=True)
data7['date']=pd.to_datetime(data7['date'])
data7['date']=data7['date'].dt.strftime('%m/%d/%y')
data7['risk-assessment-nih']=data7['risk-assessment-nih'].str.lower()

data8.columns=data8.columns.str.strip().str.lower().str.replace(' ','-')
data8.drop(['no-heading'],axis=1,inplace=True)
data8['date']=pd.to_datetime(data8['date'])
data8['date']=data8['date'].dt.strftime('%m/%d/%y')

data9.columns=data9.columns.str.strip().str.lower().str.replace(' ','-')
data9.drop(['no_heading'],axis=1,inplace=True)
data9['date']=pd.to_datetime(data9['date'])
data9['date']=data9['date'].dt.strftime('%m/%d/%y')

data10.columns=data10.columns.str.strip().str.lower().str.replace(' ','-')
data10.drop(['no_heading'],axis=1,inplace=True)
data10['date']=pd.to_datetime(data9['date'])
data10['date']=data10['date'].dt.strftime('%m/%d/%y')

writer =pd.ExcelWriter('final.xlsx')
data1.to_excel(writer,index=False,sheet_name='TimeSeries_KeyIndicators')
data2.to_excel(writer,index=False,sheet_name='TimeSeries_KeyIndicators_Detail')
data3.to_excel(writer,index=False,sheet_name='TimeSeries_Action_Screen')
data4.to_excel(writer,index=False,sheet_name='TimeSeries_Action_Call')
data5.to_excel(writer,index=False,sheet_name='TimeSeries_COVID_News')
data6.to_excel(writer,index=False,sheet_name='TimeSeries_NIH_Response')
data7.to_excel(writer,index=False,sheet_name='TimeSeries_NIH_Risk')
data8.to_excel(writer,index=False,sheet_name='TimeSeries_Province_Response')
data9.to_excel(writer,index=False,sheet_name='TimeSeries_Helpline_Calls')
data10.to_excel(writer,index=False,sheet_name='TimeSeries_Quarantine_Details')
#workbook=writer.bookworksheet=writer.sheets['TimeSeries_KeyIndicators','TimeSeries_Action_Screen','TimeSeries_Action_Call','TimeSeries_COVID_News','TimeSeries_NIH_Response','TimeSeries_NIH_Risk','TimeSeries_Helpline_Calls','TimeSeries_Quarantine_Details','TimeSeries_Province_Response']
writer.save()

